/* Copy all Code and RUN with your MySQL Server */

CREATE DATABASE dmart_store_management_system;

USE dmart_store_management_system;

CREATE TABLE UOM(
    UOM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UOM_NAME VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ORDERS(
    ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    DATETIME DATETIME NOT NULL
)ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE PRODUCTS(
    PRODUCT_ID  INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    UOM_ID INT NOT NULL,
    PRICE_PER_UNIT double NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    KEY FK_UOM_ID_IDX (UOM_ID),
    CONSTRAINT `FK_UOM_ID` FOREIGN KEY (UOM_ID) REFERENCES UOM (UOM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ORDER_DETAILS (
    ORDER_ID int NOT NULL,
    PRODUCT_ID int NOT NULL,
    QUANTITY int NOT NULL,
    TOTAL_PRICE double NOT NULL,
    PRIMARY KEY (ORDER_ID),
    KEY _PRFKODUCT_ID_IDX (PRODUCT_ID),
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON UPDATE RESTRICT,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON UPDATE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

